var mongoose= require("mongoose");
var cardbschema = new mongoose.Schema({
            CarId:Number,
            MilesTraveled: Number,
            AverageSpeed:Number,
            CarLifeSpaninYear:Number,
            LastServiceDate: Date,
            MilesDuringLastService: Number,
            MilesBetweenServices: Number,
            EngineId:Number,
            EngineManufactureDate: Date,
            EngineLifeSpaninYears:Number,
            EngineLifeSpaninPercentage:Number, //Recommend when to get it changed
            DaysSinceEngineLastService:Number,
            EngineDaysOld:Number,
            AirFilterDaysOld:Number,
            FuelFilterDaysOld:Number,
            BrakeFluidDaysOld:Number,
            CoolantDaysOld: Number,
            DaysSinceGearBoxLastService: Number,
            BatteryDaysOld: Number,
            TransmissionFluidDaysOld: Number,
            TransmissionFluidTemperature: Number,
            BatteryTemperature: Number,
            EngineSparkPlugType: String, //Sometimes Iriduim
            CableMilesUsed: Number,
            TimingBeltMilesUsed: Number,
            EngineSparkPlugMilesUsed:Number,
            PowerSteeringFluidMilesUsed: Number,
            HosesMilesUsed: Number,
            ClutchPlateMilesUsed: Number,
            TransmissionFluidMilesUsed: Number,
            CoolantMilesUsed: Number,
            BrakeRotersMilesUsed: Number,
            BrakeFluidMilesUsed:Number,
            EngineServiceNeeded: Boolean,
            AirFilterServiceNeeded: Boolean,
            FuelFilterServiceNeeded: Boolean,
            BrakeFluidServiceNeeded: Boolean,
            BrakePadServiceNeeded: Boolean,
            BrakeRotersServiceNeeded: Boolean,
            CoolantServiceNeeded: Boolean,
            TransmissionFluidServiceNeeded: Boolean,
            GearBoxServiceNeeded: Boolean,
            ClutchPlateServiceNeeded: Boolean,
            HosesServiceNeeded: Boolean,
            PowerSteeringServiceNeeded: Boolean,
            EngineSparkPlugServiceNeeded: Boolean,
            TimingBeltServiceNeeded:Boolean,
            CabelServiceNeeded: Boolean,
            BatteryServiceNeeded: Boolean,
            CarServiceNeeded: Boolean,
            Serviced: Boolean

});

module.exports = mongoose.model("Cardb", cardbschema);